/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myhand_HandUtils */

#ifndef _Included_com_example_myhand_HandUtils
#define _Included_com_example_myhand_HandUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myhand_HandUtils
 * Method:    nativeSkinTest
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_example_myhand_HandUtils_nativeSkinTest
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
