/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myhand_HelloFloat */

#ifndef _Included_com_example_myhand_HelloFloat
#define _Included_com_example_myhand_HelloFloat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myhand_HelloFloat
 * Method:    myPrint
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_example_myhand_HelloFloat_myPrint
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
