/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iron_grayprocess_ImageProc */

#ifndef _Included_com_iron_grayprocess_ImageProc
#define _Included_com_iron_grayprocess_ImageProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iron_grayprocess_ImageProc
 * Method:    grayProc
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_iron_grayprocess_ImageProc_grayProc
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_iron_grayprocess_ImageProc
 * Method:    procPic
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_iron_grayprocess_ImageProc_procPic
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
